import React from 'react';
import { InvitationData } from '../../types';

export const InvitationPreview = ({ data, id }: { data: InvitationData, id: string }) => {
  return (
    <div 
      id={id}
      className="w-[500px] p-8 bg-white border-[12px] border-double border-gold-600 shadow-2xl mx-auto"
      style={{ minHeight: '650px', borderColor: '#D4AF37' }} // Custom Imena Gold
    >
      <div className="text-center border-b pb-4 mb-6">
        <h2 className="text-sm uppercase tracking-widest text-gray-500">Imena Family Presents</h2>
        <h1 className="text-3xl font-serif font-bold text-slate-800 mt-2">{data.title || "Event Title"}</h1>
        <p className="text-blue-600 font-semibold">{data.subFamily}</p>
      </div>

      <div className="space-y-6 text-center">
        <div>
          <p className="text-gray-500 uppercase text-xs">When</p>
          <p className="text-lg font-medium">{data.date} at {data.time}</p>
        </div>
        
        <div>
          <p className="text-gray-500 uppercase text-xs">Where</p>
          <p className="text-lg font-medium">{data.location}</p>
        </div>

        <div className="bg-slate-50 p-4 rounded-lg italic">
          <p className="text-gray-500 uppercase text-xs not-italic mb-2">Agenda</p>
          <p>{data.agenda || "No agenda specified yet."}</p>
        </div>
      </div>

      <div className="mt-12 text-center text-sm text-gray-400">
        <p>Generated by Imena Paper Pop</p>
      </div>
    </div>
  );
};